### PR TITLE
Add installer and auto-update

### PR DESCRIPTION
**Pull request by rvost**
I added Clowd.Squirrel ([more about it in repo](https://github.com/clowd/Clowd.Squirrel)) wizard-free installer with auto-update feature. The release process is now as simple as pushing SemVer tag (e.g. `0.0.1` ) and then approving release draft. The user's installation will be automatically updated the next time the application is launched after release.

I've changed tag format from **v**X.X.* to just X.X.* (no prefix) to simplify workflow, because `Squirrel.exe` doesn't allow prefixes in version parameter. I hope it's not a big deal because there are no tags in the repo yet and you can choose an arbitrary format.

*\* release under `0.0.0` version actually isn't supported by nuget and so Squirrel*

### CODE REVIEW

**Comment by rvost** [comment]
Currently `pack` options defined in workflow config file:

https://github.com/rvost/PboExplorer-BisUtils/blob/467f203708f888be59a4c06d4d578794181bd538/.github/workflows/release.yml#L35-L41

It might be better to put it in a separate shell script and call it from CI. This way, changes to package configuration (e.g. adding new app icon) will be scoped to the script, not to the workflow config. Unfortunately, this idea only come to me when I was writing this PR.

**Comment by FlipperPlz** [comment]
>* release under 0.0.0 version actually isn't supported by nuget and so Squirrel.

This is no biggie, v0.0.1 would work just as well to signify that its not completely ready for usage yet.
 
>It might be better to put it in a separate shell script and call it from CI. This way, changes to package configuration (e.g. adding new app icon) will be scoped to the script, not to the workflow config. Unfortunately, this idea only come to me when I was writing this PR.

 Ahh yea I see what you mean, I may get around to changing this sometime today.

Just pushed some updates to BisUtils on NuGet, so today I will be more focused on getting everything up-to-date with the new BisUtils versions. Editing support is currently my main priority ontop of a somewhat decent tabbed GUI for viewing entries. I'm not planning on making it too perfect, just something to get the ball rolling so I can start incrementing the version of this project.

**Comment by rvost** [comment]
I was planning to add CI automation to BisUtils today, but got sidetracked and haven't started yet. It seems it's a little late now😅...

**Comment by FlipperPlz** [comment]
Its never too late xP
Alot of the code in BisUtils could use some updates, but its not too big of a deal as I will get around to rewriting alot of it sometime soon.

**Pull request merged**
