### PR TITLE
Add Github Actions workflow to automate release process

### PR DESCRIPTION
**Pull request by rvost**
This is adaptation of my contribution to Jetelain's PboExplorer. 

Quality of Life Improvement: Sets up a workflow that creates a release draft on semver-looking tag (`v*`) with single portable (framework-dependent) `.exe`.

`marvinpinto/action-automatic-releases` action also generates a changelog for the release from the last tag, which looks like following:

release_screen

P.S. Looks like `.gitignore` is missing so I added it.

### CODE REVIEW

**Comment by rvost** [comment]
Also, are you interested in adding install and auto-update features that are best implemented early on? I can do it and fit into the Actions workflow.

**Comment by FlipperPlz** [comment]
That would be great @rvost, already LGTM! I never got around to setting up the github actions so its great that you got that done. As for the installer, yes I do plan to incorporate one aswell as a simple autoupdate feature that just checks github releases for new versions. Similar to how updates are done in @wrdg DayZExtract repository but a little more in depth.

**Comment by rvost** [comment]
I have positive experience with `Squirrel`/ [Clowd.Squirrel](https://www.nuget.org/packages/Clowd.Squirrel). It has one-click install and works with GH Release out of the box. I can easily add it if you'd like.

**Comment by FlipperPlz** [comment]
For sure you can start with that. Currently the program is versioned at 0.0.0 because of how many incomplete features are added. I still need to do some small fixes to BisUtils to support editing properly. I thought I had it implemented correctly but I have to go back and do some debugging to fix things without entirely breaking projects that already depend on the current version (if any exist). The aim of this program is an all in one PBO editor with a tabbed gui and access to advanced pbo information. Basically the notepad++ of pbo viewers. Im learning WPF ui design as I go so we'll see where this ends up.

**Comment by FlipperPlz** [comment]
https://github.com/FlipperPlz/BisUtils/commit/e48225a6f9cf9c1770581604ad23e4a0c09e4ca5
BisUtils has just been fixed so my progress on this repository should resume shortly

**Pull request merged**
