### PR TITLE
Start migration to MVVM

### PR DESCRIPTION
**Pull request by rvost**
Glad to hear your response in #6 ! Today I started refactoring according to plan outlined in #7. 

Initially, I planned to wire some libraries (for mvvm and probably for [interactivity](https://www.nuget.org/packages/Microsoft.Xaml.Behaviors.Wpf)), add infrastructure boilerplate (DI, `appsettings` etc) and clean some TODOs. But I realized that it won't be beneficial before splitting `PboExplorerWindow`'s code-behind. So I started breaking it into view models and it took longer than I expected.

I opened this PR to let you know, and I'll keep it as a draft until I've scaffolded VMs for `PboExplorerWindow`.

### CODE REVIEW

**Comment by rvost** [comment]
So far I've encountered strange issue with evaluation of `CanExecute` predicate of  `RelayCommands` in [SplashViewModel](https://github.com/rvost/PboExplorer-BisUtils/blob/9af2bb525825dd3230ea3acaf57d4d79506e205d/PboExplorer/Windows/Splash/Views/RecentFiles/ViewModels/SplashViewModel.cs#L53-L55). Commands from `MRULib` work and from `CommunityToolkit.Mvvm` don't. This looks like parameter binding issue and needs more thorough debugging. So I leave those two commands intact for now.

**Comment by rvost** [comment]
I scaffolded view models and views and now we need to introduce `EntryTreeManager` service to move further because it needs to be accessible from multiple places in the app. The problem is that it has to be initialized with `PboFile` and I'm not sure if this is possible with the CommunityToolkit's IoC container.

UPD: I deferred decision about IoC container for later stages. For now use the instance created in `PboExplorerWindow` constructor but this solution seems very wrong to me.

**Comment by FlipperPlz** [comment]
I will be creating a new branch, wpf that will be up to date with your chore/infrastructure branch. 
>. The problem is that it has to be initialized with PboFile and I'm not sure if this is possible with the CommunityToolkit's IoC container.

I thought about this earlier on and was stumped for abit. I'll have to look around for some sort of solution to this. As with adding the MVVM library, I'm fine with it and was planning on adding it anyways.

As always, your work is much appreciated @rvost

**Comment by FlipperPlz** [comment]
Correction, your commits are now held at chore/infrastructure rather than wpf. I figured your branch name is much more streamline

**Comment by rvost** [comment]
In fact, I also chose a misleading branch name. I thought it would be a work focused on adding useful libraries and putting them all together before implementing MVVM. But after I replaced MRULib's `RelayCommands` and handmade `INotifyPropertyChanged` I didn't see the benefit of introducing more complex stuff.

So I jumped right into the refactoring, and I don't think there's much work left before we move on from refactoring to new features. There are only a couple of (not implemented) commands left in `PboExplorerWindow`.

**Pull request closed without merging**
